# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2024, Julian Bartholomeyczik
# All rights reserved.

# Battery Management Dashboard
title: Battery Management System
views:
  - title: Overview
    path: overview
    icon: mdi:view-dashboard
    cards:
      # --- HEADER: AT A GLANCE ---
      - type: horizontal-stack
        cards:
          # Battery Gauge
          - type: gauge
            entity: sensor.batterie_soc
            name: Battery
            min: 0
            max: 100
            severity:
              green: 50
              yellow: 20
              red: 0
            needle: true

          # Current Price
          - type: sensor
            entity: sensor.tibber_energy_prices
            name: Price
            graph: line
            detail: 1

          # Solar Remaining
          - type: sensor
            entity: sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
            name: Solar Left
            graph: line
            detail: 1

      # --- MAIN GRID ---
      - type: horizontal-stack
        cards:
          # COLUMN 1: BATTERY STATUS
          - type: vertical-stack
            cards:
              - type: entities
                title: Battery Status
                show_header_toggle: false
                entities:
                  - entity: sensor.charging_state
                    name: State
                  - entity: input_number.battery_target_soc
                    name: Target SoC
                  - entity: sensor.computed_target_soc
                    name: Smart Target
                    icon: mdi:target-account
                  - type: divider
                  - entity: input_boolean.battery_charging_active
                    name: Charging Active
                  - entity: input_boolean.battery_no_discharging_active
                    name: Discharge Limited

              - type: history-graph
                title: SoC History (24h)
                hours_to_show: 24
                entities:
                  - entity: sensor.batterie_soc
                    name: SoC
                  - entity: sensor.computed_target_soc
                    name: Smart Target

          # COLUMN 2: ECONOMICS
          - type: vertical-stack
            cards:
              - type: entities
                title: Economics
                show_header_toggle: false
                entities:
                  - entity: binary_sensor.charging_is_profitable
                    name: Profitable to Charge
                  - type: divider
                  - entity: sensor.tibber_energy_lowest_price_next_24_hours
                    name: 24h Low
                  - entity: sensor.tibber_energy_highest_price_next_24_hours
                    name: 24h High
                  - entity: sensor.tibber_energy_price_percentile_next_12_hours
                    name: Price Percentile (12h)

              - type: history-graph
                title: Price History
                hours_to_show: 24
                entities:
                  - entity: sensor.tibber_energy_prices
                    name: Price

          # COLUMN 3: CONTROLS & HEALTH
          - type: vertical-stack
            cards:
              - type: entities
                title: Wallbox & Car
                show_header_toggle: false
                entities:
                  - entity: sensor.wattpilot_carconnected
                    name: Status
                  - entity: select.wattpilot_charging_mode
                    name: Mode
                  - type: divider
                  - entity: input_boolean.battery_no_discharging_active
                    name: Discharge Limited (Car)

              - type: entities
                title: Controls
                show_header_toggle: false
                entities:
                  - entity: input_boolean.battery_automation_on
                    name: Automation Enabled
                  - entity: input_boolean.manual_battery_charge
                    name: Manual Charge
                  - entity: input_number.manual_charge_target_soc
                    name: Manual Target

              - type: entities
                title: Logic & Health
                show_header_toggle: false
                entities:
                  - entity: binary_sensor.should_start_charging
                    name: Should Start
                  - entity: binary_sensor.should_stop_charging
                    name: Should Stop
                  - type: divider
                  - entity: binary_sensor.tibber_pulse_not_functioning
                    name: Tibber Pulse Status

  # --- OTHER VIEWS (KEPT FOR DETAIL) ---
  - title: Charging Logic
    path: charging_logic
    icon: mdi:lightning-bolt
    cards:
      - type: entities
        title: Charging Decision Logic
        entities:
          - entity: binary_sensor.should_start_charging
            name: Should Start Charging
          - entity: binary_sensor.should_stop_charging
            name: Should Stop Charging
          - entity: sensor.computed_target_soc
            name: Computed Target SoC
          - type: divider
          - entity: sensor.battery_soc_threshold_high
            name: SoC Threshold (High)
          - entity: sensor.battery_soc_threshold_low
            name: SoC Threshold (Low)
          - entity: sensor.battery_soc_normalized
            name: Current SoC (Normalized)

      - type: entities
        title: Solar Forecast
        entities:
          - entity: binary_sensor.expected_sun_low
            name: Expected Sun Low
          - entity: binary_sensor.expected_sun_very_low
            name: Expected Sun Very Low
          - entity: sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
            name: Remaining Today
          - entity: sensor.solcast_pv_forecast_forecast_next_x_hours
            name: Forecast Next Hours

      - type: entities
        title: Wallbox (Car Charging)
        entities:
          - entity: sensor.wattpilot_carconnected
            name: Car Status
          - entity: select.wattpilot_charging_mode
            name: Charging Mode

  - title: Configuration
    path: configuration
    icon: mdi:cog
    cards:
      - type: entities
        title: Target SoC Settings
        entities:
          - entity: input_number.soc_target_very_low_sun
            name: Target (Very Low Sun)
          - entity: input_number.soc_target_low_sun
            name: Target (Low Sun)
          - entity: input_number.soc_target_default
            name: Target (Default)
          - entity: input_number.soc_hist
            name: SoC Hysteresis

      - type: entities
        title: Solar Forecast Thresholds
        entities:
          - entity: input_number.sun_threshold_low
            name: Low Sun Threshold
          - entity: input_number.sun_threshold_very_low
            name: Very Low Sun Threshold

      - type: entities
        title: Manual Control Scripts
        entities:
          - entity: script.start_battery_charging
            name: Start Charging
            icon: mdi:battery-charging
          - entity: script.stop_battery_charging
            name: Stop Charging
            icon: mdi:battery-off
          - entity: script.start_limit_discharging
            name: Limit Discharge
            icon: mdi:battery-lock
          - entity: script.stop_limit_discharging
            name: Stop Limit Discharge
            icon: mdi:battery-unlock
          - type: divider
          - entity: script.set_regular_charge
            name: Set Regular Charge
          - entity: script.forced_half_recharge
            name: Force Half Recharge
          - entity: script.forced_full_recharge
            name: Force Full Recharge

  - title: Monitoring
    path: monitoring
    icon: mdi:chart-line
    cards:
      - type: history-graph
        title: Battery State of Charge (24h)
        hours_to_show: 24
        entities:
          - entity: sensor.batterie_soc
            name: Battery SoC
          - entity: input_number.battery_target_soc
            name: Target SoC
          - entity: sensor.computed_target_soc
            name: Computed Target

      - type: history-graph
        title: Charging State (24h)
        hours_to_show: 24
        entities:
          - entity: input_boolean.battery_charging_active
            name: Charging Active
          - entity: input_boolean.battery_no_discharging_active
            name: Discharge Limited
          - entity: binary_sensor.should_start_charging
            name: Should Start Charging

      - type: history-graph
        title: Price vs Solar Forecast (24h)
        hours_to_show: 24
        entities:
          - entity: sensor.tibber_energy_prices
            name: Energy Price
          - entity: binary_sensor.expected_sun_low
            name: Sun Low
          - entity: binary_sensor.expected_sun_very_low
            name: Sun Very Low

      - type: entities
        title: System Health
        entities:
          - entity: binary_sensor.tibber_pulse_not_functioning
            name: Tibber Pulse Status
          - type: section
            label: Notifications
          - type: markdown
            content: |
              **Active Alerts:**
              - Battery charging notifications
              - Low battery alerts (< 7.5%)
              - Tibber Pulse connectivity issues

  - title: Advanced
    path: advanced
    icon: mdi:tune
    cards:
      - type: entities
        title: Advanced Modbus Controls
        entities:
          - entity: script.set_limited_discharge
            name: Set Limited Discharge
          - entity: script.half_regular_charge
            name: Half Regular Charge
          - entity: script.discharge_at_half_rate
            name: Discharge at Half Rate

      - type: entities
        title: All Control Flags
        entities:
          - entity: input_boolean.battery_charging_active
          - entity: input_boolean.battery_no_discharging_active
          - entity: input_boolean.battery_automation_on
          - entity: input_boolean.manual_charging_on
          - entity: input_boolean.manual_battery_charge

      - type: markdown
        title: System Information
        content: |
          ## Hardware Setup
          - **Inverter:** Fronius Gen24 6.0
          - **Battery:** BYD Battery Pack
          - **Wallbox:** Wattpilot
          - **Energy Monitor:** Tibber Pulse

          ## Algorithm Features
          - Dynamic SoC targeting based on solar forecast
          - Price-based charging optimization
          - Car charging coordination
          - Hysteresis to prevent charge cycling

          ## Documentation
          See README.md for complete setup and configuration details.
